receivers:
# OpenTelemetry Protocol 
  otlp:
    protocols:
      grpc:
        endpoint: ${env:MY_POD_IP}:4317
        # endpoint: 0.0.0.0:4317
      http:
        endpoint: ${env:MY_POD_IP}:4318
        # endpoint: 0.0.0.0:4318

  # https://opentelemetry.io/docs/kubernetes/collector/components/
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8sclusterreceiver
  # **IMPORTANT NOTICE**:
  # this will have to move to its own collector as we really just want one of these running or we will duplicate the data
  k8s_cluster:
    auth_type: serviceAccount
    collection_interval: 10s
    metadata_collection_interval: 5m
    node_conditions_to_report: [Ready, DiskPressure, MemoryPressure, PIDPressure, NetworkUnavailable]
    allocatable_types_to_report: [cpu, memory, ephemeral-storage, storage]

  # TODO: Prometheus Receiver https://opentelemetry.io/docs/kubernetes/collector/components/#prometheus-receiver
  # TODO: Kubernetes Objects Receiver https://opentelemetry.io/docs/kubernetes/collector/components/#kubernetes-objects-receiver
  
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/syslogreceiver/README.md
  syslog/rfc5424:
    tcp:
      listen_address: ${env:MY_POD_IP}:54526
    udp:
      listen_address: ${env:MY_POD_IP}:54527
    protocol: rfc5424 #rfc3164
    enable_octet_counting: false
    allow_skip_pri_header: false
    location: UTC

    # option for handling tls here
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/syslogreceiver/README.md
  syslog/rfc5424tls:
    tcp:
      listen_address: ${env:MY_POD_IP}:54528
      tls:
        cert_file: /etc/otelcol-contrib/secrets/gw-observability-test-pndrs-de.crt
        key_file: /etc/otelcol-contrib/secrets/gw-observability-test-pndrs-de.key
        #ca_file:
        #client_ca_file:
    protocol: rfc5424
    enable_octet_counting: false
    allow_skip_pri_header: false
    location: UTC

  # syslog/rfc5424tlst:
  #   tcp:
  #     listen_address: ${env:MY_POD_IP}:54529
  #   protocol: rfc5424
  #   enable_octet_counting: false
  #   allow_skip_pri_header: false
  #   location: UTC

  # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/syslogreceiver/README.md
  syslog/rfc3164:
    tcp:
      listen_address: ${env:MY_POD_IP}:54528
    udp:
      listen_address: ${env:MY_POD_IP}:54529
    protocol: rfc3164 
    enable_octet_counting: false
    allow_skip_pri_header: false
    location: UTC

  prometheus:
    config:
      scrape_configs:
        - job_name: otel-frr-exporter
          static_configs:
            - targets:
                - 192.168.0.100:9480
          metrics_path: /metrics
          scrape_interval: 15s
        - job_name: otel-node-exporter
          static_configs:
            - targets:
                - 192.168.0.100:9481
          metrics_path: /metrics
          scrape_interval: 5s
        - job_name: blackbox-exporter
          static_configs:
            - targets:
                - 192.168.0.100:9115
          metrics_path: /metrics
          scrape_interval: 5s

exporters:
  debug: {}
  prometheus:
    endpoint: 0.0.0.0:8889

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [debug, prometheus]
