receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:MY_POD_IP}:4317
      http:
        endpoint: ${env:MY_POD_IP}:4318

  # https://opentelemetry.io/docs/kubernetes/collector/components/
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8sclusterreceiver
  # **IMPORTANT NOTICE**:
  # this will have to move to its own collector as we really just want one of these running or we will duplicate the data
  k8s_cluster:
    auth_type: serviceAccount
    collection_interval: 10s
    metadata_collection_interval: 5m
    node_conditions_to_report: [Ready, DiskPressure, MemoryPressure, PIDPressure, my-networkUnavailable]
    allocatable_types_to_report: [cpu, memory, ephemeral-storage, storage]

  # TODO: Prometheus Receiver https://opentelemetry.io/docs/kubernetes/collector/components/#prometheus-receiver
  # TODO: Kubernetes Objects Receiver https://opentelemetry.io/docs/kubernetes/collector/components/#kubernetes-objects-receiver

  # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/syslogreceiver/README.md
  syslog/rfc5424:
    tcp:
      listen_address: ${env:MY_POD_IP}:54526
    udp:
      listen_address: ${env:MY_POD_IP}:54527
    protocol: rfc5424 #rfc3164
    enable_octet_counting: false
    allow_skip_pri_header: false
    location: UTC

  # option for handling tls here
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/syslogreceiver/README.md
  syslog/rfc5424tls:
    tcp:
      listen_address: ${env:MY_POD_IP}:54528
      tls:
        # cert_file: /etc/otelcol-contrib/secrets/gw-observability-test-pndrs-de.crt
        # key_file: /etc/otelcol-contrib/secrets/gw-observability-test-pndrs-de.key
        #ca_file:
        #client_ca_file:
    protocol: rfc5424
    enable_octet_counting: false
    allow_skip_pri_header: false
    location: UTC

  # syslog/rfc5424tlst:
  #   tcp:
  #     listen_address: ${env:MY_POD_IP}:54529
  #   protocol: rfc5424
  #   enable_octet_counting: false
  #   allow_skip_pri_header: false
  #   location: UTC

  # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/syslogreceiver/README.md
  syslog/rfc3164:
    tcp:
      listen_address: ${env:MY_POD_IP}:54530 # Changed port to avoid conflict
    udp:
      listen_address: ${env:MY_POD_IP}:54529
    protocol: rfc3164
    enable_octet_counting: false
    allow_skip_pri_header: false
    location: UTC

  # Vyos SNMP
  # https://confluence.bare.pandrosion.org/pages/viewpage.action?pageId=190612318#POCSyslogMessagingforObservability-ObservabilityMeasures
  # debug
  # k port-forward svc/prom-snmp-exporter 9116:9116
  # curl 'http://localhost:9116/snmp?module=hrSystem&module=system&module=if_mib&target=er-2613e3531e2348a087063887378c2a0f.default-doe.stable.pndrs.de&auth=vyos'
  # curl 'http://localhost:9116/snmp?module=vyos_system&target=er-2613e3531e2348a087063887378c2a0f.default-doe.stable.pndrs.de&auth=vyos'
  prometheus/vyos:
    config:
      scrape_configs:
        #local tests jobs
        - job_name: otel-frr-exporter
          static_configs:
            - targets:
                - 192.168.0.100:9480
          metrics_path: /metrics
          scrape_interval: 15s
        - job_name: otel-node-exporter
          static_configs:
            - targets:
                - 192.168.0.100:9481
          metrics_path: /metrics
          scrape_interval: 5s
        - job_name: blackbox-exporter
          static_configs:
            - targets:
                - 192.168.0.100:9115
          metrics_path: /metrics
          scrape_interval: 5s

        # Global exporter-level metrics
        - job_name: snmp_exporter
          static_configs:
            - targets: ['prom-snmp-exporter:9116']
        - job_name: snmp
          static_configs:
            - targets:
                - er-2613e3531e2348a087063887378c2a0f.default-doe.stable.pndrs.de
                - er-2516c83242e043ea93c56fc04589075f.doe.stable.pndrs.de
                - er-39a82c2460804a0c99868ce5ca779300.zerocarbon-1.stable.pndrs.de
          metrics_path: /snmp
          params:
            auth:
              - vyos
            # we may still need to filter these
            module:
              # SNMPv2-MIB
              # https://mibbrowser.online/mibdb_search.php?mib=SNMPv2-MIB
              # https://github.com/prometheus/snmp_exporter/blob/16185db0f330e5e6eadf8cd83741cde80320edfe/snmp.yml#L42025
              - system

              # IF-MIB
              # https://mibbrowser.online/mibdb_search.php?mib=IF-MIB
              # https://github.com/prometheus/snmp_exporter/blob/16185db0f330e5e6eadf8cd83741cde80320edfe/snmp.yml#L22378
              - if_mib

              # HOST-RESOURCES-MIB
              # https://mibbrowser.online/mibdb_search.php?mib=HOST-RESOURCES-MIB
              # https://github.com/prometheus/snmp_exporter/blob/16185db0f330e5e6eadf8cd83741cde80320edfe/snmp.yml#L22342
              - hrSystem
              - hrSWRunPerf
              - hrStorage
              - hrSWRun

          relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - source_labels: [__param_target]
              target_label: instance
            - target_label: __address__
              replacement: prom-snmp-exporter:9116 # The SNMP exporter's real hostname:port.

            # add vyos exporters
        - job_name: frr_exporter
          static_configs:
            - targets:
                - er-2613e3531e2348a087063887378c2a0f.default-doe.stable.pndrs.de
                - er-2516c83242e043ea93c56fc04589075f.doe.stable.pndrs.de
                - er-39a82c2460804a0c99868ce5ca779300.zerocarbon-1.stable.pndrs.de
          metrics_path: /metrics
          relabel_configs:
            # 1. add port 9342 to targets
            - source_labels: [__address__]
              regex: (.*) # target all
              replacement: $1:9342 # add port
              target_label: __address__ # replace address

            # 2. set instance without port
            - source_labels: [__address__] # get address with port
              regex: (.*):9342 # match address with port
              target_label: instance # set instance
              replacement: $1 # replace with address without port

        - job_name: blackbox_exporter
          static_configs:
            - targets:
                - er-2613e3531e2348a087063887378c2a0f.default-doe.stable.pndrs.de
                - er-2516c83242e043ea93c56fc04589075f.doe.stable.pndrs.de
                - er-39a82c2460804a0c99868ce5ca779300.zerocarbon-1.stable.pndrs.de
          metrics_path: /metrics
          relabel_configs:
            # 1. add port 9115 to targets
            - source_labels: [__address__]
              regex: (.*) # target all
              replacement: $1:9115 # add port
              target_label: __address__ # replace address

            # 2. set instance without port
            - source_labels: [__address__] # get address with port
              regex: (.*):9115 # match address with port
              target_label: instance # set instance
              replacement: $1 # replace with address without port

        - job_name: node_exporter
          static_configs:
            - targets:
                - er-2613e3531e2348a087063887378c2a0f.default-doe.stable.pndrs.de
                - er-2516c83242e043ea93c56fc04589075f.doe.stable.pndrs.de
                - er-39a82c2460804a0c99868ce5ca779300.zerocarbon-1.stable.pndrs.de
          metrics_path: /metrics
          relabel_configs:
            # 1. add port 9481 to targets
            - source_labels: [__address__]
              regex: (.*) # target all
              replacement: $1:9481 # add port
              target_label: __address__ # replace address

            # 2. set instance without port
            - source_labels: [__address__] # get address with port
              regex: (.*):9481 # match address with port
              target_label: instance # set instance
              replacement: $1 # replace with address without port

exporters:
  debug: {}
  prometheus:
    endpoint: 0.0.0.0:8889
service:
  pipelines:
    metrics:
      receivers: [prometheus/vyos]
      exporters: [debug, prometheus] # Corrected: changed 'prometheus/vyos' to 'prometheus'