receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-frr-exporter
          static_configs:
            - targets:
                - 192.168.0.100:9480
          metrics_path: /metrics
          scrape_interval: 15s
        - job_name: otel-node-exporter
          static_configs:
            - targets:
                - 192.168.0.100:9481
          metrics_path: /metrics
          scrape_interval: 5s
        - job_name: blackbox-exporter
          static_configs:
            - targets:
                - 192.168.0.100:9115
          metrics_path: /metrics
          scrape_interval: 5s

exporters:
  debug: {}
  prometheus:
    endpoint: 0.0.0.0:8889

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [debug, prometheus]
